#!/bin/bash

failures=0
RC=0

subhook_root=hooks/commit_hooks
tmptree=$(mktemp -d)

while read oldrev newrev refname; do
    git archive $newrev | tar x -m -C ${tmptree}
    for changedfile in $(git diff --name-only $oldrev $newrev --diff-filter=ACM); do
        tmpmodule="$tmptree/$changedfile"

        if type python >/dev/null 2>&1; then
            #check yaml syntax
            if [ $(echo $changedfile | grep -q '\.*.yaml$\|\.*.yml$'; echo $?) -eq 0 ]; then 
                ${subhook_root}/yaml_syntax_check.sh $tmpmodule "${tmptree}/"
                RC=$?
                if [ "$RC" -ne 0 ]; then
                    failures=`expr $failures + 1`
                fi
            fi
        else
            echo "python not installed. Skipping yaml checks..."
        fi
    done
done
rm -rf ${tmptree}

#summary
if [ "$failures" -ne 0 ]; then
    echo -e "\x1B[0;31mError: $failures subhooks failed. Declining push.\x1B[0m"
    exit 1
fi

exit 0
