#!/bin/bash

git_root=`git rev-parse --show-toplevel`
failures=0
RC=0

subhook_root=$git_root/.git/hooks/commit_hooks

hook_dir="$(dirname $0)"
hook_symlink="$(readlink $0)"

# Figure out where commit hooks are if pre-commit is setup as a symlink
if [ ! -z "$hook_symlink" ]; then
  subhook_root="$(dirname $hook_symlink)/commit_hooks"
fi

# If using submodules, we need to read proper subhook root
if [ -f "$git_root/.git" ]; then
    IFS=": "
    while read -r name value
    do
        if [ $name == "gitdir" ]; then
            submodule_hookdir=$value
        fi
    done < "$git_root/.git"
    if [ ! -z "$submodule_hookdir" ]; then
        subhook_root="$git_root/$submodule_hookdir/hooks/commit_hooks"
    fi
fi

for changedfile in `git diff --cached --name-only --diff-filter=ACM`; do
    if type python >/dev/null 2>&1; then
        #check yaml syntax
        if [ $(echo $changedfile | grep -q '\.*.ya\?ml$'; echo $?) -eq 0 ]; then
            ${subhook_root}/yaml_syntax_check.sh $changedfile
            RC=$?
            if [ "$RC" -ne 0 ]; then
                failures=`expr $failures + 1`
            fi
        fi
    else
        echo "python not installed. Skipping yaml checks..."
    fi
done

#summary
if [ "$failures" -ne 0 ]; then
    echo -e "\x1B[0;31mError: $failures subhooks failed. Aborting commit.\x1B[0m"
    exit 1
fi

exit 0
